"""add LIKE TABLE

Revision ID: 98d15e6412d4
Revises: 9db2de9b5581
Create Date: 2024-11-18 22:27:20.957101

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "98d15e6412d4"
down_revision: Union[str, None] = "9db2de9b5581"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
