"""add all tabs

Revision ID: 9db2de9b5581
Revises: 3fbcb37f5dd5
Create Date: 2024-11-18 22:24:50.593312

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "9db2de9b5581"
down_revision: Union[str, None] = "3fbcb37f5dd5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
