"""init

Revision ID: fabd68a7b998
Revises:
Create Date: 2024-11-11 17:11:19.318618

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "fabd68a7b998"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
