repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Use the latest stable version
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-docstring-first
      - id: name-tests-test
      - id: requirements-txt-fixer

  - repo: https://github.com/psf/black
    rev: 24.10.0  # Use the latest stable version
    hooks:
      - id: black
        language_version: python3  # Specify Python version

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2  # Use the latest stable version
    hooks:
      - id: isort
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1  # Use the latest stable version
    hooks:
      - id: flake8
        additional_dependencies: [ flake8-pyproject ]  # Добавьте этот плагин для поддержки pyproject.toml
  #
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args: [ "--remove-all-unused-imports", "--in-place" ]
#  - repo: https://github.com/python/mypy
#    rev: v1.13.0 # specify the version you want to use
#    hooks:
#      - id: mypy
#        additional_dependencies: # optional, add any additional dependencies if needed
#          - types-atomicwrites
#          - types-tabulate
#          - types-freezegun
