[tool.black]
line-length = 120
target-version = ["py312", ]
exclude = "venv"

[tool.isort]
profile = "black"
combine_as_imports = true
multi_line_output = 3
skip = ["venv", ]
line_length = 120

[tool.autoflake]
check = false
in-place = true
recursive = true
exclude = ".venv/*,app/migrations/*"
remove-all-unused-imports = true
ignore-init-module-imports = true
remove-duplicate-keys = true
remove-unused-variables = true

[tool.flake8]
max-line-length = 120  # Установите желаемую максимальную длину строки
ignore = ["E203", "E266", "E501","D104","D100","D106","D105"]  # Игнорируйте определенные ошибки
exclude = [
    ".venv/*",        # Исключаем все файлы в папке .venv
    "__pycache__/*",  # Исключаем все файлы в папке __pycache__
    "build/*",        # Исключаем все файлы в папке build
    "dist/*",         # Исключаем все файлы в папке dist
    "app/migrations/*"    # Исключаем все файлы в папке migrations
]
builtins = ["Tweet"]

[tool.mypy]
plugins = ["pydantic.mypy"]
exclude = "^(test/|tests/)"
follow_imports = "silent"
warn_redundant_casts = true
warn_unused_ignores = true
disallow_any_generics = true
check_untyped_defs = true
no_implicit_reexport = true
