name: CI/CD Pipeline correct

on:
  push:
    branches:
      - main
      - ci
  pull_request:
    branches:
      - main
      - ci

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu image
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      #          pip install pytest  # Install Pytest and other dependencies as needed

      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=$(pwd):$(pwd)" >> $GITHUB_ENV

      - name: Verify PYTHONPATH
        run: |
          echo "PYTHONPATH=$PYTHONPATH"
          python -c "import sys; print(sys.path)"

      - name: List directory contents
        run: |
          ls -R
      - name: Run unit tests
        run: python -m pytest tests

      - name: Run MyPy type checking
        run: mypy .
      - name: Run Black formatting check
        run: black --diff --check .
      - name: Run Isort check
        run: isort --check-only .
      - name: Run Flake8 linting
        run: flake8 .
