name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - ci
  pull_request:
    branches:
      - main
      - сш
  workflow_dispatch:
    inputs:
      check_type:
        description: 'Choose the type of check to run'
        required: true
        default: 'all'
        options:
          - all
          - tests
          - type_checking
          - formatting_checks
          - isort_checks
          - flask8

jobs:
  run_checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=$(pwd):$(pwd)" >> $GITHUB_ENV

      - name: Verify PYTHONPATH
        run: |
          echo "PYTHONPATH=$PYTHONPATH"
          python -c "import sys; print(sys.path)"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: List directory contents
        run: |
          ls -R


      # Условный шаг для выполнения тестов в зависимости от параметра
      - name: Run unit tests
        if: ${{ github.event.inputs.check_type == 'all' || github.event.inputs.check_type == 'tests' }}
        run: pytest tests

      # Условный шаг для выполнения проверки типов в зависимости от параметра
      - name: Run MyPy type checking
        if: ${{ github.event.inputs.check_type == 'all' || github.event.inputs.check_type == 'type_checking' }}
        run: mypy .

      # Условный шаг для выполнения проверок форматирования в зависимости от параметра
      - name: Run Black formatting check
        if: ${{ github.event.inputs.check_type == 'all' || github.event.inputs.check_type == 'formatting_checks' }}
        run: black --diff --check .

      - name: Run Isort check
        if: ${{ github.event.inputs.check_type == 'all' || github.event.inputs.check_type == 'isort_checks' }}

        run: isort --check-only .

      - name: Run Flake8 linting
        if: ${{ github.event.inputs.check_type == 'all' || github.event.inputs.check_type == 'flake8' }}

        run: flake8 .

      # Добавьте дополнительные проверки по аналогии...