name: Linters Pipeline

on:
  push:
    branches:
      - main
      - dev2
  pull_request:
    branches:
      - main
      - dev2

jobs:
  setup:
    uses: ./.github/workflows/setup-python.yml  # Call the reusable workflow
    with:
      python-version: '3.12'  # Specify the Python version

  test:
      runs-on: ubuntu-latest
      needs: setup  # This job depends on the setup job НО все равно надо заново устанавливать библиотеки на каждую job
      steps:
        - name: Checkout version
          run: python3.12 -V
