name: Linters Pipeline

on:
  push:
    branches:
      - main
      - dev2
  pull_request:
    branches:
      - main
      - dev2

jobs:
  mypy:
      runs-on: ubuntu-latest
#      needs: test  # This job depends on the setup job
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Run MyPy type checking
          run: mypy .

  black:
      runs-on: ubuntu-latest
#      needs: mypy  # This job depends on the setup job
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Run Black formatting check
          run: black --diff --check .

  isort:
      runs-on: ubuntu-latest
#      needs: black  # This job depends on the setup job
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Run Isort check
          run: isort --check-only .

  flake8:
      runs-on: ubuntu-latest
#      needs: isort
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Run Flake8 linting
          run: flake8 .

  tests:
    runs-on: ubuntu-latest
    needs: [ mypy, black, isort, flake8 ]  # Зависит от всех линтеров
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest  # Или другая команда для запуска тестов, если вы используете другую библиотеку тестирования.
