name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - ci
  pull_request:
    branches:
      - main
      - ci

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=$(pwd):$(pwd)" >> $GITHUB_ENV

  test:
    runs-on: ubuntu-latest
    needs: setup  # This job depends on the setup job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run unit tests
        run: python -m pytest tests

  mypy:
    runs-on: ubuntu-latest
    needs: setup  # This job depends on the setup job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run MyPy type checking
        run: mypy .

  black:
    runs-on: ubuntu-latest
    needs: setup  # This job depends on the setup job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Black formatting check
        run: black --diff --check .

  isort:
    runs-on: ubuntu-latest
    needs: setup  # This job depends on the setup job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Isort check
        run: isort --check-only .

  flake8:
    runs-on: ubuntu-latest
    needs: setup  # This job depends on the setup job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Flake8 linting
        run: flake8 .
