name: CI/CD Pipeline new

on:
  push:
    branches:
      - main
      - ci
  pull_request:
    branches:
      - main
      - ci

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=$(pwd):$(pwd)" >> $GITHUB_ENV

      - name: Verify PYTHONPATH
        run: |
          echo "PYTHONPATH=$PYTHONPATH"
          python -c "import sys; print(sys.path)"

      - name: List directory contents
        run: |
          ls -R

  run_tests:
    runs-on: ubuntu-latest
    needs: setup  # Эта job зависит от job setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run unit tests
        run: python -m pytest tests

  type_checking:
    runs-on: ubuntu-latest
    needs: setup  # Эта job также зависит от job setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run MyPy type checking
        run: mypy .

  formatting_checks:
    runs-on: ubuntu-latest
    needs: setup  # Эта job также зависит от job setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Black formatting check
        run: black --diff --check .

      - name: Run Isort check
        run: isort --check-only .

  flake8_checks:
    runs-on: ubuntu-latest
    needs: setup  # Эта job также зависит от job setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Flake8 linting
        run: flake8 .
