name: Setup Python and Install Dependencies # Просто название проверки, это переиспользуемый workflow

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 #Копирование кода в рабочую среду гита

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }} #установка питона

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

#      - name: Set PYTHONPATH
#        run: |
#          echo "PYTHONPATH=$(pwd):$(pwd)" >> $GITHUB_ENV

#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1


#      - name: Build and run Docker Compose
#        run: |
#          echo "Creating .env file"
#          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
#          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
#          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
#          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
#          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
#          echo "DB_TEST=${{ secrets.DB_TEST }}" >> .env
#          echo "UPLOAD_DIRECTORY=${{ secrets.UPLOAD_DIRECTORY }}" >> .env
#          echo "PYTHONPATH=${{ secrets.PYTHONPATH }}" >> .env
#
#          echo "Contents of .env file:"
#          cat .env
#
#      - name: Build and run Docker Compose
#        run: |
#          docker compose up --build -d

#      - name: Run Alembic Migrations
#        run: |
#          # Wait for the database service to be ready (optional, but recommended)
#          sleep 10  # Adjust this time as necessary based on your database startup time
#
#          # Run Alembic migrations inside the running container
#          docker exec <your_container_name> alembic -x db=test upgrade head
