name: CI/CD Pipeline Test & Linters

on:
  push:
    branches:
      - main
      - dev2
  pull_request:
    branches:
      - main
      - dev2

jobs:
  setup:
    uses: ./.github/workflows/setup-python2.yml  # Переиспользуемый workflow
    with:
      python-version: '3.12'

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: .env file create
        run: |
          echo "Creating .env file"
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_TEST=${{ secrets.DB_TEST }}" >> .env
          echo "UPLOAD_DIRECTORY=${{ secrets.UPLOAD_DIRECTORY }}" >> .env
          echo "PYTHONPATH=${{ secrets.PYTHONPATH }}" >> .env

      - name: .env file check
        run: |
          echo "Contents of .env file:"
          cat .env

      - name: Build and run Docker Compose
        run: |
          docker compose up --build -d

      - name: Run Alembic Migrations
        run: |
          sleep 10  # Подождите, пока база данных будет готова (опционально)
          docker exec <your_container_name> alembic -x db=test upgrade head

      - name: Run unit tests
        run: python -m pytest tests

#  mypy:
#    runs-on: ubuntu-latest
#    needs: setup
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Run MyPy type checking
#        run: mypy .
#
#  black:
#    runs-on: ubuntu-latest
#    needs: setup
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Run Black formatting check
#        run: black --diff --check .
#
#  isort:
#    runs-on: ubuntu-latest
#    needs: setup
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Run Isort check
#        run: isort --check-only .
#
#  flake8:
#    runs-on: ubuntu-latest
#    needs: setup
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Run Flake8 linting
#        run: flake8 .
