name: CI/CD Pipeline Test & Linters

on:
  push:
    branches:
      - main
      - dev2
  pull_request:
    branches:
      - main
      - dev2

jobs:
  setup:
    uses: ./.github/workflows/setup-python2.yml  # Переиспользуемый workflow
    with:
      python-version: '3.12'

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download .env file artifact
        uses: actions/download-artifact@v3
        with:
          name: env-file

      - name: Build and run Docker Compose
        run: |
          docker compose up --build -d

      - name: Run Alembic Migrations
        run: |
          sleep 10  # Подождите, пока база данных будет готова (опционально)
          docker exec <your_container_name> alembic -x db=test upgrade head

      - name: Run unit tests
        run: python -m pytest tests

#  mypy:
#    runs-on: ubuntu-latest
#    needs: setup
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Run MyPy type checking
#        run: mypy .
#
#  black:
#    runs-on: ubuntu-latest
#    needs: setup
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Run Black formatting check
#        run: black --diff --check .
#
#  isort:
#    runs-on: ubuntu-latest
#    needs: setup
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Run Isort check
#        run: isort --check-only .
#
#  flake8:
#    runs-on: ubuntu-latest
#    needs: setup
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Run Flake8 linting
#        run: flake8 .
